CREATE TABLE SHOE
(
SHOE_ID INTEGER,
SHOE_NAME VARCHAR(20),
BRAND_NAME VARCHAR(20),
PRICE INTEGER,
CREATED_BY VARCHAR(20),
CREATED_DATE DATE,
MODIFIED_BY VARCHAR(20),
MODIFIED_DATE DATE,
PRIMARY KEY (SHOE_ID)
);

INSERT INTO SHOE VALUES (1,'GEL NIMBUS','Asics',10000, 'arun', CURRENT_DATE , 'arun' ,CURRENT_DATE );
INSERT INTO SHOE VALUES (2,'GEL KINSEI','Asics','13000');
INSERT INTO SHOE VALUES (3,'GEL CUMULUS','Asics','8000');
INSERT INTO SHOE VALUES (4,'GEL KAYANO','Asics','11000');
INSERT INTO SHOE VALUES (0,'Evo Speed','Puma','6000');
INSERT INTO SHOE VALUES (5,'Adiboost','Adidas','8000');
INSERT INTO SHOE VALUES (6,'Air Max','Nike','14000');


CREATE TABLE USER_CREDS
(
USERID VARCHAR(20),
PASSWORD VARCHAR(20),
PRIMARY KEY (USERID),
FOREIGN KEY (USERID) REFERENCES USER_DETAILS (USERID)
);

INSERT INTO USER_CREDS VALUES ('arun','shoe123');

CREATE TABLE USER_DETAILS
(
USERID VARCHAR(20),
FIRSTNAME VARCHAR(20),
LASTNAME VARCHAR(20),
USERROLE VARCHAR(20),
ADDRESSID VARCHAR(20),
PRIMARY KEY (USERID),
FOREIGN KEY (ADDRESSID) REFERENCES USER_ADDRESS (ADDRESSID)
);

INSERT INTO USER_DETAILS VALUES ('arun','arun','mohan','Admin','123');
INSERT INTO USER_DETAILS VALUES ('raj','raj','raj','ADMIN','123');
INSERT INTO USER_DETAILS VALUES ('ram','ram','ram','VIEW','123');




CREATE TABLE USER_ADDRESS
(
ADDRESSID VARCHAR(20),
CITY VARCHAR(20),
STATE VARCHAR(20),
COUNTRY VARCHAR(20),
ZIPCODE VARCHAR(20),
PRIMARY KEY (ADDRESSID)
);

INSERT INTO USER_ADDRESS VALUES ('123','abc','abc','abc','abc');

CREATE TABLE USER_PHONE
(
PHONEID VARCHAR(20),
PHONENO VARCHAR(20),
USERID VARCHAR(20),
PRIMARY KEY (PHONEID),
FOREIGN KEY (USERID) REFERENCES USER_DETAILS (USERID)
);

INSERT INTO USER_PHONE VALUES ('123','123','arun');


CREATE TABLE USER_EMAIL
(
EMAILID VARCHAR(20),
EMAIL VARCHAR(20),
USERID VARCHAR(20),
PRIMARY KEY (EMAILID),
FOREIGN KEY (USERID) REFERENCES USER_DETAILS (USERID)
);

INSERT INTO USER_EMAIL VALUES ('123','arun@gmail','arun');

DROP TABLE SHOE_IMAGE;
CREATE TABLE SHOE_IMAGE
(
SHOE_ID INTEGER,
SHOE_IMAGE BLOB
);

---SAMPLES

CREATE TABLE LICENSE
(
LICENSEID VARCHAR(20),
LICENSETYPE VARCHAR(20),
PRIMARY KEY (LICENSEID)
);

CREATE TABLE DRIVER
(
DRIVERID VARCHAR(20),
DRIVERNAME VARCHAR(20),
LICENSEID VARCHAR(20),
PRIMARY KEY (DRIVERID),
FOREIGN KEY (LICENSEID) REFERENCES LICENSE (LICENSEID)
);

CREATE TABLE AUTHOR
(
AUTHORID VARCHAR(20),
AUTHORNAME VARCHAR(20),
PRIMARY KEY (AUTHORID)
);

CREATE TABLE BOOK
(
BOOKID VARCHAR(20),
BOOKNAME VARCHAR(20),
AUTHORID VARCHAR(20),
PRIMARY KEY (BOOKID),
FOREIGN KEY (AUTHORID) REFERENCES AUTHOR (AUTHORID)
);