CREATE TABLE SHOE
(
SHOE_ID INTEGER,
SHOE_NAME VARCHAR(20),
BRAND_NAME VARCHAR(20),
PRICE INTEGER,
CREATED_BY VARCHAR(20),
CREATED_DATE DATE,
MODIFIED_BY VARCHAR(20),
MODIFIED_DATE DATE,
PRIMARY KEY (SHOE_ID)
);

INSERT INTO SHOE VALUES (1,'GEL NIMBUS','Asics',10000, 'arun', CURRENT_DATE , 'arun' ,CURRENT_DATE);


